name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - develop
      - main

env:
  WORKING_DIRECTORY: app

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ env.WORKING_DIRECTORY }}/package.json
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install Node Dependencies
        run: npm ci
      - name: Build storybook
        run: npm run build-storybook
      - name: Set up basic auth
        run: |
          echo "AuthType Basic" >> ${{ env.WORKING_DIRECTORY }}/storybook-static/.htaccess
          echo "AuthName \"Restricted Area\"" >> ${{ env.WORKING_DIRECTORY }}/storybook-static/.htaccess
          echo "AuthUserFile /etc/apache2/.htpasswd" >> ${{ env.WORKING_DIRECTORY }}/storybook-static/.htaccess
          echo "Require valid-user" >> ${{ env.WORKING_DIRECTORY }}/storybook-static/.htaccess
          htpasswd -bc ${{ env.WORKING_DIRECTORY }}/storybook-static/.htpasswd ${{ secrets.BASIC_AUTH_USER }} ${{ secrets.BASIC_AUTH_PASSWORD }}
      - name: Upload Documents
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.WORKING_DIRECTORY }}/storybook-static
